Akollade/mjml-bundle

README.md
composer.json
src/DependencyInjection/Configuration.php
src/DependencyInjection/MjmlExtension.php
src/Mjml.php
src/Resources/config/services.yml
src/Twig/Extension.php
src/Twig/Node.php
src/Twig/TokenParser.php

Clear code
Remove deprecated method (ProcessBuilder)
Add dependency
Update Readme
I suggest creating a v2.0.0 tag for this version which is compatible with SF4
And create a tag v1.0.0 for the version before the merge of this PR SF <4

Add compatibility with SF4

---

.travis.yml

Enable travis integration

---

README.md
src/Mjml.php

Check presence and version of MJML, handle validation for mjml 3 and 4

---

.gitignore
.travis.yml
README.md
composer.json
phpunit.xml.dist
src/DependencyInjection/Configuration.php
src/DependencyInjection/MjmlExtension.php
src/Renderer/BinaryRenderer.php
src/Renderer/RendererInterface.php
src/Resources/config/services.yml
src/SwiftMailer/MjmlPlugin.php
src/Twig/Extension.php
src/Twig/TokenParser.php
tests/AbstractTestCase.php
tests/Renderer/BinaryRendererTest.php
tests/fixtures/basic.mjml

Renderer interface

---

src/Renderer/BinaryRenderer.php

Check MJML version only one time

---

src/Renderer/BinaryRenderer.php

Fix mimify for mjml 4

---

CHANGELOG.md

Update changelog for the next version

---

src/Twig/Extension.php
src/Twig/Node.php
src/Twig/TokenParser.php

Fix Twig deprecations

---

src/Resources/config/services.yml

Fix indentation

---

.travis.yml

Add PHP 7.3 in travis

---

CHANGELOG.md
src/DependencyInjection/Configuration.php

Fix deprecation for symfony/config 4.2+

---

src/Twig/Extension.php
src/Twig/TokenParser.php
tests/Twig/ExtensionTest.php

* Test the Twig extension
* Fix issue with the last version of Twig

Add test for rendering with twig extension

---

.travis.yml
composer.json
ecs.yaml
src/DependencyInjection/Configuration.php
src/DependencyInjection/MjmlExtension.php
src/Renderer/BinaryRenderer.php
src/Renderer/RendererInterface.php
src/SwiftMailer/MjmlPlugin.php
src/Twig/Extension.php
src/Twig/Node.php
src/Twig/TokenParser.php
tests/AbstractTestCase.php
tests/Configuration/ConfigurationTest.php

Replace PHP-CS-Fixer with EasyCodingStandard

---

.travis.yml

Refactor travis config and add PHP 7.4

---

README.md

Use SF Mailer syntax for examples

---

README.md
src/SwiftMailer/MjmlPlugin.php

The Swiftmailer integration is deprecated

---

src/Twig/Extension.php
src/Twig/Node.php
src/Twig/TokenParser.php

:bug: Clean Twig tag to fix issues with last versions of Twig

---

CHANGELOG.md
README.md
src/DependencyInjection/Configuration.php
src/DependencyInjection/MjmlExtension.php
src/Renderer/BinaryRenderer.php
tests/AbstractTestCase.php
tests/Renderer/BinaryRendererTest.php

Add option to set path to node

---

.github/workflows/tests.yaml
composer.json

Allow PHP 8

---

src/DependencyInjection/MjmlExtension.php

Add return void in MjmlExtension

---

.github/workflows/cs.yaml
.github/workflows/tests.yaml

Update cache composer steps to fix deprecations

---

src/Twig/Node.php

Fix #90
See https://github.com/twigphp/Twig/issues/4034

Adapt Twig node to remove usage of ob_start with Twig 3.9

---

src/Twig/Node.php

Fix deprecation with Twig Node / yield

---

.github/workflows/tests.yaml

Add PHP 8.3 / 8.4 in CI
